# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bricks & Pieces helper
email: info@bbqsoftwares.com
description: > # this means to ignore newlines until "baseurl:"
  LEGO® is a trademark of The LEGO Group of companies which does not sponsor, authorize or endorse this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bricks.bbqsoftwares.com" # the base hostname & protocol for your site

EurobricksLink : "http://www.eurobricks.com/forum/index.php?showtopic=121587&#entry2471034"

# Build settings
markdown: kramdown

# https://github.com/stereobooster/jekyll-press
jekyll-press:
  exclude: 'css/dropzone.css' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options